# Site settings
author: Terrell Murrell
title: 
header-img: img/home-bg.png
email: littlerell12@gmail.com
copyright_name: Terrell Murrell
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tmurrell2020

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
